-- Hand-written, not Hibernate-generated: DataSeeder inserts through raw JDBC and needs to
-- know the exact table and column names, and relying on ddl-auto to match that by
-- convention is exactly the kind of implicit coupling this project avoids elsewhere.
--
-- GENERATED BY DEFAULT AS IDENTITY is ANSI SQL:2003, supported natively by both H2 2.x and
-- PostgreSQL 10+, so this file runs unmodified against either (see application.yml and
-- application-postgres.yml).

CREATE TABLE IF NOT EXISTS category (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS product (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id  BIGINT NOT NULL REFERENCES category (id),
    name         VARCHAR(200) NOT NULL,
    description  VARCHAR(2000),
    price_cents  BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory (
    product_id          BIGINT PRIMARY KEY REFERENCES product (id),
    stock_count         INT NOT NULL,
    warehouse_location  VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS review (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL REFERENCES product (id),
    rating      INT NOT NULL,
    comment     VARCHAR(1000)
);

CREATE INDEX IF NOT EXISTS idx_product_category_id ON product (category_id);
CREATE INDEX IF NOT EXISTS idx_review_product_id ON review (product_id);
